ministryofjustice/help-with-prison-visits-asynchronous-worker

app/services/data/get-task-counts-by-status.js, app/web/app.js, package.json, test/integration/services/data/test-get-task-counts-by-status.js, test/test-helper.js, test/unit/web/test-app.js
chore - add task count to status
=> chore - add task count to status

app/process-tasks.js, app/services/data/complete-task-with-status.js, app/services/data/get-pending-tasks-and-mark-inprogress.js, app/services/data/get-task-counts-by-status.js, app/services/domain/task.js, test/integration/services/data/test-complete-task-with-status.js, test/integration/services/data/test-get-pending-tasks-and-mark-inprogress.js, test/integration/services/data/test-get-task-counts-by-status.js, test/unit/services/domain/test-task.js, test/unit/test-process-tasks.js
chore - check internal schema for tasks
=> chore - check internal schema for tasks

app/services/data/copy-first-time-claim-data-to-internal.js, test/integration/services/data/test-copy-first-time-claim-data-to-internal.js, test/test-helper.js
=> bug - cost was retrieved as string copied without decimals

test/test-helper.js
=> chore - removed Visitor.RequireBenefitUpload

app/services/data/copy-first-time-claim-data-to-internal.js, app/services/data/delete-first-time-claim-from-external.js, app/services/data/get-all-first-time-claim-data.js, test/integration/services/data/test-copy-first-time-claim-data-to-internal.js, test/integration/services/data/test-get-all-first-time-claim-data.js, test/test-helper.js
Added functionality to allow ClaimChild table contents to be copied.
Updated the test-helper to handle the ClaimChild table.
Updated affected tests.
Removed done calls from edited tests.
=> Added functionality to allow ClaimChild table contents to be copied.

app/services/data/copy-first-time-claim-data-to-internal.js, test/integration/services/data/test-insert-task-dwp-check.js
Fixed copy. It was not copying child details.
Fixed the after in one of the tests it was not executing as expected.
=> Fixed copy. It was not copying child details over to internal.

app/services/data/copy-first-time-claim-data-to-internal.js, app/services/data/delete-first-time-claim-from-external.js, app/services/data/get-all-first-time-claim-data.js, test/integration/services/data/test-get-all-first-time-claim-data.js, test/test-helper.js
Added logic to move claim document from external to internal
=> Feature - Apvs 672 - moving claim document from external to internal

app/constants/claim-type-enum.js, app/services/auto-approval/auto-approval-process.js, app/services/auto-approval/checks/are-children-under-18.js, app/services/auto-approval/checks/has-claimed-less-than-max-times-this-year.js, app/services/auto-approval/checks/has-uploaded-prison-visit-confirmation-and-receipts.js, app/services/auto-approval/checks/is-claim-submitted-within-time-limit.js, app/services/auto-approval/checks/is-claim-total-under-limit.js, app/services/auto-approval/checks/is-visit-in-past.js, app/services/data/get-data-for-auto-approval-check.js, app/services/notify/helpers/group-expenses-by-type.js, test/unit/services/auto-approval/test-are-children-under-18.js, test/unit/services/auto-approval/test-auto-approval-process.js, test/unit/services/auto-approval/test-has-uploaded-prison-visit-confirmation-and-receipts.js
=> chore - bug fixes on async worker to allow first-time claim and repeats

app/process-tasks.js, app/services/log.js
=> chore - add error log serialiser

test/integration/services/data/test-auto-approve-claim.js
=> removed multiple claim test data and added new checks

test/integration/services/data/test-update-claims-processed-payment.js
=> fix update-claims-processed-payment integration test

test/unit/services/auto-approval/checks/test-are-children-under-18.js, test/unit/services/auto-approval/checks/test-cost-and-variance-equal-or-less-than-first-time-claim.js, test/unit/services/auto-approval/checks/test-do-expenses-match-first-time-claim.js, test/unit/services/auto-approval/checks/test-has-claimed-less-than-max-times-this-year.js, test/unit/services/auto-approval/checks/test-has-uploaded-prison-visit-confirmation-and-receipts.js, test/unit/services/auto-approval/checks/test-is-claim-submitted-within-time-limit.js, test/unit/services/auto-approval/checks/test-is-claim-total-under-limit.js, test/unit/services/auto-approval/checks/test-is-latest-manual-claim-approved.js, test/unit/services/auto-approval/checks/test-is-no-previous-pending-claim.js, test/unit/services/auto-approval/checks/test-is-prison-not-in-guernsey-jersey.js, test/unit/services/auto-approval/checks/test-is-visit-in-past.js, test/unit/services/auto-approval/checks/test-visit-date-different-to-previous-claims.js
=> chore - move auto-approval check tests to correct folder

app/services/auto-approval/auto-approval-process.js, app/services/data/get-data-for-auto-approval-check.js, test/integration/services/data/test-get-data-for-auto-approval-check.js, test/unit/services/auto-approval/test-auto-approval-process.js
=> apvs-208 - disable auto-approval for advance claims

app/constants/deduction-type-enum.js, app/services/data/get-approved-claim-expense-data.js, app/services/data/get-enabled-claim-deductions.js, app/services/notify/helpers/get-approved-claim-details-string.js, app/services/workers/send-accepted-claim-notification.js, test/integration/services/data/test-get-approved-claim-expense-data.js, test/test-helper.js, test/unit/services/notify/helpers/test-get-approved-claim-details-string.js, test/unit/services/workers/test-send-accepted-claim-notification.js
Updated accepted claim notification so that it will now include any enabled deductions and caseworker comments.
- Modified claim accepted email template to include the case worker if applicable
- Added deduction-type-enum (same as one in internal)
- Updated get-approved-claim-expense-data - removed reference parameter, now also returns case worker note for claim
- Updated get-approved-claim-details-string, will now append deductions if any exist
=> Feature/apvs 861/hc3 deductions

app/process-tasks.js, config.js
Worker was using Payment cron env value if supplied, so if configured on dev/test it would only run once a day.
=> updated env to use unique name and string on batch size

docker-compose.yml
Fixed typo in the docker compose file.
=> Fixed bug in docker compose file that caused it to fail to run.

app/constants/claim-type-enum.js, app/services/auto-approval/auto-approval-process.js, test/unit/services/auto-approval/test-auto-approval-process.js
=> issue 73 - should fail auto-approval for repeat new eligibility claims

app/services/workers/send-request-information-claim-notification.js, config.js, test/unit/services/workers/test-send-request-information-claim-notification.js
=> add requestInfoUrl data to request information notification

app/services/auto-approval/auto-approval-process.js, app/services/data/auto-approve-claim.js, app/services/data/copy-claim-data-to-internal.js, app/services/data/disable-claim-document.js, app/services/data/get-claim-documents.js, app/services/data/insert-claim-event.js, app/services/data/move-claim-documents-to-internal.js, app/services/notify/helpers/generate-claim-updated-string.js, app/services/workers/request-information-response.js, test/integration/services/data/test-auto-approve-claim.js, test/integration/services/data/test-disable-claim-document.js, test/integration/services/data/test-get-claim-documents.js, test/integration/services/data/test-insert-claim-event.js, test/integration/services/data/test-move-claim-documents-to-internal.js, test/unit/services/notify/helpers/test-generate-claim-updated-string.js, test/unit/services/workers/test-request-information-response.js
- disable old documents for new documents in request information flow
- add claim event per disabled document
=> Feature/apvs 373/insert claim event per upload document

app/services/data/auto-approve-claim.js, test/integration/services/data/test-auto-approve-claim.js
=> On Auto approval approve visit confirmation

test/test-helper.js
=> chore - remove title

test/test-helper.js, test/unit/services/auto-approval/checks/test-are-children-under-18.js
Updated all points in the application, database queries, and tests referencing the old Name field.
=> Split the child 'Name' field into 'FirstName' and 'LastName' fields.

app/constants/auto-approval-rules-enum.js
=> Added missing checks to auto-approval-rules-enum

app/services/auto-approval/checks/cost-and-variance-equal-or-less-than-first-time-claim.js, test/unit/services/auto-approval/checks/test-cost-and-variance-equal-or-less-than-first-time-claim.js
=> Retrieve ApprovedCost from previous claim when working out cost variance

app/services/auto-approval/checks/are-children-under-18.js, app/services/auto-approval/checks/has-claimed-less-than-max-times-this-month.js, app/services/auto-approval/checks/has-claimed-less-than-max-times-this-year.js, app/services/auto-approval/checks/is-visit-in-past.js, app/services/data/auto-approve-claim.js, app/services/data/get-old-payment-files.js, app/services/date-formatter.js, app/services/direct-payments/create-payment-file.js, app/services/workers/mark-overpayments.js, test/integration/services/data/test-get-advance-claims-total-expense-approved-cost-before-date.js, test/integration/services/data/test-get-auto-approval-config.js, test/integration/services/data/test-get-claims-pending-payment.js, test/integration/services/data/test-get-data-for-auto-approval-check.js, test/integration/services/data/test-get-old-payment-files.js, test/test-helper.js, test/unit/services/auto-approval/checks/test-are-children-under-18.js, test/unit/services/auto-approval/checks/test-has-claimed-less-than-max-times-this-month.js, test/unit/services/auto-approval/checks/test-has-claimed-less-than-max-times-this-year.js, test/unit/services/auto-approval/checks/test-is-claim-submitted-within-time-limit.js, test/unit/services/auto-approval/checks/test-is-visit-in-past.js
Modified all code that uses moment to get the current date/time to use the date formatter instead.
Closes #92 .
=> Added date-formatter to ensure correct date/times for DST

test/unit/services/auto-approval/checks/test-has-claimed-less-than-max-times-this-year.js
Fixed failing test, updated helper function to generate correct amount of claims for test.
=> Fixed test

app/services/data/reference-number-recovery.js, app/services/workers/reference-recovery.js, test/unit/services/workers/test-reference-recovery.js
Updated personalisation of email content
* Updated DB call to get firstname as well
* Updated worker to send firstname and url
=> Updated content of recovery email personalisation

app/constants/payment-method-enum.js, app/services/data/copy-claim-data-to-internal.js, app/services/workers/request-information-response.js
Checks payment method before attempting to copy bank details
=> Made copy methods capable of handling no bank details incase of payout

app/services/direct-payments/create-payment-file.js, app/services/payout-payments/create-payout-file.js, app/services/workers/generate-direct-payments.js, test/unit/services/workers/test-generate-direct-payments.js
Added logging to say how many payments made in files, and then a check on direct payments to not continue if there is no sort code or account number associated with files
=> Added logging and check on direct payment

app/services/cleanup-old-data/delete-old-payment-files.js, test/integration/services/cleanup-old-data/test-delete-old-payment-files.js
=> Put return of promise in delete payment files and updated test

app/services/data/complete-task-with-status.js, app/services/data/insert-claim-event.js, app/services/data/insert-direct-payment-file.js, app/services/data/insert-task.js, app/services/workers/archive-old-claims.js, app/services/workers/cleanup-old-data.js, test/integration/services/data/test-complete-task-with-status.js, test/integration/services/data/test-get-all-claims-older-than-date.js, test/integration/services/data/test-get-old-claim-data.js, test/integration/services/data/test-get-old-claim-document-data.js, test/integration/services/data/test-get-old-eligibility-data.js, test/integration/services/data/test-insert-direct-payment-file.js, test/integration/services/data/test-insert-task.js, test/integration/services/data/test-update-old-payment-files-is-enabled-false.js, test/test-helper.js, test/unit/services/workers/test-archive-old-claims.js, test/unit/services/workers/test-request-information-response.js, test/unit/services/workers/test-send-performance-platform-metrics-for-day.js
Made update to use date formatter on all dates using current time so that DST is applied
=> Updated to use dateformatter for current time

app/services/distance-checker/calculate-car-expense-costs.js, test/unit/services/distance-checker/test-calculate-car-expense-costs.js
Updated to make toPostCode null if no toPostcode entered and destination is not prison
=> feature/apvs 1399/update to car journey for another route

app/services/workers/send-feedback.js, app/services/workers/send-technical-help.js
=> Updating zendesk enabled

app/services/workers/send-feedback.js, app/services/workers/send-technical-help.js
=> Removing logging of full result

app/services/workers/send-feedback.js, app/services/workers/send-technical-help.js
=> Updating to email updates on tickets

app/services/workers/send-feedback.js, app/services/workers/send-technical-help.js
=> Feature/apvs 1542/zendesk api

app/services/workers/send-feedback.js, app/services/workers/send-technical-help.js
=> Updated requester

app/services/workers/send-feedback.js, app/services/workers/send-technical-help.js
=> Adding auto email verification

app/services/workers/send-technical-help.js
=> Updating subjects for email notifications

app/services/workers/send-feedback.js, app/services/workers/send-technical-help.js
=> Adding tags and adding submitter as helpwithprisonvisits agent account

app/services/auto-approval/checks/is-claim-submitted-within-time-limit.js, test/unit/services/auto-approval/checks/test-is-claim-submitted-within-time-limit.js
=> Feature/apvs 0018/auto approval

app/constants/prisons-enum.js
=> APVS0019: Update to prison enums with new postcode for LeyHill.

.gitignore, app/services/direct-payments/create-adi-journal-file.js, python/adi_generator/adi_config.py, test/unit/services/workers/test-generate-direct-payments.js
Reverts ministryofjustice/apvs-asynchronous-worker#194
=> Revert "APVS-0016: Update to change references to adi journal from xlsm to xl…"

python/adi_generator/adi_config.py
=> Updating configuration values to point at xls instead of xlsm

app/services/data/auto-approve-claim.js, app/services/data/get-claims-pending-payment.js, test/integration/services/data/test-auto-approve-claim.js, test/integration/services/data/test-get-claims-pending-payment.js
=> Feature/apvs 0067/add date approved field to claim

app/constants/dwp-failed-email-enum.js, app/services/workers/dwp-check.js, app/services/workers/send-technical-help.js
=> Feature/apvs 0062/dwp check additional info

app/services/data/get-visitor-dwp-benefit-checker-data.js, app/services/workers/dwp-check.js
Adding email as a returned result to dwp benefit checker data
Updating email to send dwp additional information required to
Making the note on the claim internal
=> Updating email address to send to

app/services/workers/dwp-check.js
=> Coding standard fix

app/services/workers/generate-payout-payments.js
=> Changing payout file template

test/integration/services/data/test-insert-task.js, test/integration/services/distance-checker/test-call-distance-api-for-postcodes.js, test/integration/services/payout-payments/test-create-payout-file.js
=> Updating tests

app/constants/dwp-check-result-enum.js, app/services/workers/complete-claim.js, app/services/workers/dwp-check.js, test/unit/services/workers/test-complete-claim.js, test/unit/services/workers/test-dwp-check-failure.js, test/unit/services/workers/test-dwp-check.js
=> Feature/apvs 0115/move auto approval

test/integration/services/data/test-get-data-for-auto-approval-check.js
=> APVS0115: Fixing Integration Tests

test/integration/services/data/test-get-data-for-auto-approval-check.js
=> APVS0115: Resolving an ID conflict with Integration tests

app/services/auto-approval/checks/is-claim-submitted-within-time-limit.js, app/services/data/get-data-for-auto-approval-check.js, test/integration/services/data/test-get-data-for-auto-approval-check.js, test/unit/services/auto-approval/checks/test-is-claim-submitted-within-time-limit.js
=> Fix/apvs 0117/auto approval

test/integration/services/distance-checker/test-call-distance-api-for-postcodes.js
=> APVS0016: Updating the expected distance calculation result

app/services/direct-payments/create-payment-file.js
=> APVS0016: Changing bank payment file format from csv to txt

app/services/archiving/move-claim-data-to-archive-database.js, app/services/data/copy-claim-data-to-archive.js, app/services/data/get-all-claim-data.js, knexfile.js, test/integration/services/distance-checker/test-call-distance-api-for-postcodes.js
=> Fix/apvs 0185/archive claim task failing

test/integration/services/direct-payments/test-create-payment-file.js, test/integration/services/distance-checker/test-call-distance-api-for-postcodes.js
=> APVS0016: Fixing tests

test/integration/services/distance-checker/test-call-distance-api-for-postcodes.js
=> APVS1077: Updating the expected distance calculation result

app/services/workers/auto-approve-claims.js
=> APVS0177: Removing unnecessary then statement and log statements

test/unit/services/auto-approval/test-auto-approval-process.js
=> APVS0177: debugging auto-approve unit tests

knexfile.js
=> APVS0208: Increasing pool size and connection timeout

test/integration/services/distance-checker/test-call-distance-api-for-postcodes.js
=> APVS0176: Updating expected distance

app/services/data/get-claims-pending-payment.js, app/services/workers/generate-payout-payments.js, npm-shrinkwrap.json, test/integration/services/data/test-get-claims-pending-payment.js, test/integration/services/payout-payments/test-create-payout-file.js, test/unit/services/workers/test-generate-payout-payments.js
=> Feature/apvs 0184/visit date on payout letter

app/services/data/copy-claim-data-to-internal.js, app/services/data/delete-claim-from-external.js, app/services/data/insert-claim-event.js, app/services/data/migrate-claim-to-internal-as-transaction.js, app/services/data/update-contact-details.js, app/services/workers/complete-claim.js, test/integration/services/data/test-copy-claim-data-to-internal.js, test/integration/services/data/test-delete-claim-from-external.js, test/integration/services/data/test-migrate-claim-to-internal-as-transaction.js, test/integration/services/distance-checker/test-call-distance-api-for-postcodes.js, test/test-helper.js, test/unit/services/workers/test-complete-claim.js
SQUASHED COMMIT MESSAGE (e.g. apvs-123 - this message accurately describes my changes replacing the squashed concaHigh-level description - a few sentences on the overall context and goals for the PR's commits.
APVS0208: Copying claim to internal as a transaction. If any part of the copy operation fails, nothing will be copied. The COMPLETE-CLAIM task will terminate as FAILED
=> Fix/apvs 0208/check for duplicate claim data

test/integration/services/data/test-migrate-claim-to-internal-as-transaction.js
=> APVS0208: Logging error message for migrate integration test

app/services/data/copy-claim-data-to-archive.js, app/services/data/copy-claim-data-to-internal.js, app/services/data/delete-claim-from-external.js, app/services/data/delete-claim-from-internal.js, app/services/data/get-all-claim-data.js, test/integration/services/payout-payments/test-create-payout-file.js
=> Feature/apvs 0210/child escorts

test/integration/services/distance-checker/test-call-distance-api-for-postcodes.js
=> APVS0210: Fixing integration tests

test/integration/services/data/test-get-claims-pending-payment.js, test/integration/services/direct-payments/test-create-payment-file.js, test/integration/services/distance-checker/test-call-distance-api-for-postcodes.js, test/test-helper.js
=> Feature/apvs 0016/bank payments

app/services/workers/helpers/insert-dummy-upload-later-benefit-document.js, test/integration/services/data/test-get-data-for-auto-approval-check.js, test/test-helper.js
=> APVS0250: Updating integration tests

.circleci/config.yml, Dockerfile, README.md, package-lock.json
Switch back to node 12, node 14 and some of these modules aren't 100% compatible.
=> Switch back to node 12 for compatibility on old service

Dockerfile
=> Fix healthcheck port in Dockerfile

Dockerfile, app/web/app.js, test/integration/services/data/test-get-task-counts-by-status.js, test/unit/web/test-app.js
=> Add a basic status check

helm_deploy/help-with-prison-visits-asynchronous-worker/values.yaml, helm_deploy/values-dev.yaml
=> Remove not needed config as no ingress is required

app/services/direct-payments/create-adi-journal-file.js, app/services/direct-payments/create-payment-file.js, app/services/payout-payments/create-payout-file.js, config.js
Reverts ministryofjustice/help-with-prison-visits-asynchronous-worker#329
=> Revert "Put payment files back in payment folder in S3"

helm_deploy/help-with-prison-visits-asynchronous-worker/templates/daily-tasks-cron.yaml, helm_deploy/help-with-prison-visits-asynchronous-worker/templates/payment-run-cron.yaml, helm_deploy/help-with-prison-visits-asynchronous-worker/templates/worker-tasks-cron.yaml
Reverts ministryofjustice/help-with-prison-visits-asynchronous-worker#345
=> Revert "Remove ttlSecondsAfterFinished for live migration"

knexfile.js
Have set according to:
https://stackoverflow.com/questions/71944268/setting-the-timeout-with-knex-js-for-mssql
=> Update database connection timeout

knexfile.js
Adding connection timeout as well as request timeout since it's the original connection timeout causing an issue.... https://tediousjs.github.io/node-mssql/#general-same-for-all-drivers
=> Add connection timeout

knexfile.js
Options removed and added based on actual documentation here:
https://tediousjs.github.io/node-mssql/
https://github.com/vincit/tarn.js/#usage
=> VB-1319: Fix connection timeouts

app/azure-appinsights.js, helm_deploy/help-with-prison-visits-asynchronous-worker/values.yaml
=> VB-1325: Update AppInsights connection string

app/constants/prisons-enum.js
Added:
* Bella Centre (G20 9DR)
* Lilias Centre (G20 9DR)
* Stirling (FK9 5NU)
Removed
* Cornton Vale, which has closed.
=> Added 3 new prisons and removed one old one

helm_deploy/help-with-prison-visits-asynchronous-worker/values.yaml
=> Added productID

app/constants/prisons-enum.js
=> Added Millsike to prison list
